package tasks

import (
	"time"

	"github.com/go-core-fx/bunfx"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/schema"
)

// taskModel is the database representation using Bun ORM.
// This struct maps to the `tasks` table and is used for all database operations.
type taskModel struct {
	bun.BaseModel `bun:"table:tasks,alias:t"`
	bunfx.TimedModel

	ID          int64      `bun:"id,pk,autoincrement"`
	ProjectSlug string     `bun:"project_slug,notnull"`
	Number      int        `bun:"number,notnull"`
	Title       string     `bun:"title,notnull"`
	Description string     `bun:"description,type:text,nullzero"`
	Priority    Priority   `bun:"priority,notnull,default:'Minor'"`
	Status      Status     `bun:"status,notnull,default:'New'"`
	AuthorID    int64      `bun:"author_id,notnull"`
	AssigneeID  *int64     `bun:"assignee_id,nullzero"`
	DueDate     *time.Time `bun:"due_date,nullzero"`
	DeletedAt   *time.Time `bun:"deleted_at,soft_delete,nullzero"`
}

// newTaskModel creates a new taskModel from TaskInput and the generated task number.
func newTaskModel(input TaskInput, number int) *taskModel {
	now := time.Now()
	return &taskModel{
		BaseModel:   schema.BaseModel{},
		TimedModel:  bunfx.TimedModel{CreatedAt: now, UpdatedAt: now},
		ID:          0, // Auto-generated by database
		ProjectSlug: input.ProjectSlug,
		Number:      number,
		Title:       input.Title,
		Description: input.Description,
		Priority:    input.Priority,
		Status:      StatusNew, // Always start as "New"
		AuthorID:    input.AuthorID,
		AssigneeID:  input.AssigneeID,
		// Convert *string to *time.Time
		DueDate: func() *time.Time {
			if input.DueDate != nil {
				t, err := time.Parse(time.DateOnly, *input.DueDate)
				if err != nil {
					// Invalid date format, return nil
					return nil
				}
				return &t
			}
			return nil
		}(),
		DeletedAt: nil,
	}
}

// toDomain converts the database model to a domain Task entity.
// Returns nil if the model is nil.
func (m *taskModel) toDomain() *Task {
	if m == nil {
		return nil
	}
	return &Task{
		ID:          m.ID,
		ProjectSlug: m.ProjectSlug,
		Number:      m.Number,
		Title:       m.Title,
		Description: m.Description,
		Priority:    m.Priority,
		Status:      m.Status,
		AuthorID:    m.AuthorID,
		AssigneeID:  m.AssigneeID,
		// Convert *time.Time to *string (YYYY-MM-DD format)
		DueDate: func() *string {
			if m.DueDate != nil {
				t := m.DueDate.Format(time.DateOnly)
				return &t
			}
			return nil
		}(),
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
		DeletedAt: m.DeletedAt,
	}
}
