package comments

import (
	"time"

	"github.com/go-core-fx/bunfx"
	"github.com/uptrace/bun"
)

// commentModel is the database representation using Bun ORM.
// This struct maps to the `comments` table and is used for all database operations.
type commentModel struct {
	bun.BaseModel `bun:"table:comments,alias:c"`
	bunfx.TimedModel

	ID        int64      `bun:"id,pk,autoincrement"`
	TaskID    int64      `bun:"task_id,notnull"`
	AuthorID  int64      `bun:"author_id,notnull"`
	Content   string     `bun:"content,notnull,type:text"`
	DeletedAt *time.Time `bun:"deleted_at,soft_delete,nullzero"`
}

// newCommentModel creates a new commentModel from CommentInput.
func newCommentModel(input CommentInput) *commentModel {
	now := time.Now()
	return &commentModel{
		BaseModel:  bun.BaseModel{},
		TimedModel: bunfx.TimedModel{CreatedAt: now, UpdatedAt: now},
		ID:         0, // Auto-generated by database
		TaskID:     input.TaskID,
		AuthorID:   input.AuthorID,
		Content:    input.Content,
		DeletedAt:  nil,
	}
}

// newCommentImport creates a new commentModel for import with explicit timestamps.
func newCommentImport(input Comment) *commentModel {
	return &commentModel{
		BaseModel:  bun.BaseModel{},
		TimedModel: bunfx.TimedModel{CreatedAt: input.CreatedAt, UpdatedAt: input.UpdatedAt},
		ID:         0,
		TaskID:     input.TaskID,
		AuthorID:   input.AuthorID,
		Content:    input.Content,
		DeletedAt:  input.DeletedAt,
	}
}

// toDomain converts the database model to a domain Comment entity.
// Returns nil if the model is nil.
func (m *commentModel) toDomain() *Comment {
	if m == nil {
		return nil
	}
	return &Comment{
		ID:        m.ID,
		TaskID:    m.TaskID,
		AuthorID:  m.AuthorID,
		Content:   m.Content,
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
		DeletedAt: m.DeletedAt,
	}
}
