name: tailwind-css

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build tailwind css
        run: npx tailwindcss@3.4.17 --config tailwind.config.js -i web/static/css/input.css -o web/static/css/tailwind.css --minify

      - name: Ensure generated css is committed
        run: git diff --exit-code

